// <auto-generated />
using System;
using LancheBom.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LancheBom.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221019220409_createDbSqlite")]
    partial class createDbSqlite
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("LancheBom.Models.Adicional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Preco")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("Adicionais");
                });

            modelBuilder.Entity("LancheBom.Models.Lanche", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Preco")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Lanches");
                });

            modelBuilder.Entity("LancheBom.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LancheId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ValorPedido")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("LancheId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("LancheBom.Models.Adicional", b =>
                {
                    b.HasOne("LancheBom.Models.Pedido", null)
                        .WithMany("Adicionais")
                        .HasForeignKey("PedidoId");
                });

            modelBuilder.Entity("LancheBom.Models.Pedido", b =>
                {
                    b.HasOne("LancheBom.Models.Lanche", "Lanche")
                        .WithMany()
                        .HasForeignKey("LancheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lanche");
                });

            modelBuilder.Entity("LancheBom.Models.Pedido", b =>
                {
                    b.Navigation("Adicionais");
                });
#pragma warning restore 612, 618
        }
    }
}
